// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject_L00181476.DataAccess;

#nullable disable

namespace RP1.DataAccess.Migrations
{
    [DbContext(typeof(GolfDBContext))]
    [Migration("20260213140533_Num4")]
    partial class Num4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject_L00181476.Models.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Country")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "Titleist",
                            Country = "USA",
                            FoundedYear = 1932
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "Callaway",
                            Country = "USA",
                            FoundedYear = 1982
                        },
                        new
                        {
                            Id = 3,
                            BrandName = "TaylorMade",
                            Country = "USA",
                            FoundedYear = 1979
                        },
                        new
                        {
                            Id = 4,
                            BrandName = "Ping",
                            Country = "USA",
                            FoundedYear = 1959
                        },
                        new
                        {
                            Id = 5,
                            BrandName = "Cobra",
                            Country = "USA",
                            FoundedYear = 1973
                        });
                });

            modelBuilder.Entity("MyProject_L00181476.Models.Models.GolfBall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("GolfBalls");
                });

            modelBuilder.Entity("MyProject_L00181476.Models.Models.GolfBall", b =>
                {
                    b.HasOne("MyProject_L00181476.Models.Models.Brand", "Brand")
                        .WithMany("GolfBalls")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MyProject_L00181476.Models.Models.Brand", b =>
                {
                    b.Navigation("GolfBalls");
                });
#pragma warning restore 612, 618
        }
    }
}
